apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mlops-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50